# Change these first
owner: ZPTXDev # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Quaver
    check: "tcp-ping"
    url: $QUAVER_API_URL
    port: $QUAVER_API_PORT
    icon: https://raw.githubusercontent.com/ZPTXDev/status/master/assets/quaver.png
    maxResponseTime: 500
  - name: Quaver Dev
    check: "tcp-ping"
    url: $QUAVER_DEV_API_URL
    port: $QUAVER_DEV_API_PORT
    icon: https://raw.githubusercontent.com/ZPTXDev/status/master/assets/quaver-dev.png
    maxResponseTime: 500
  - name: Lavalink
    check: "tcp-ping"
    url: $LAVALINK_API_URL
    port: $LAVALINK_API_PORT
    icon: https://raw.githubusercontent.com/lavalink-devs/Lavalink/master/branding/lavalink.svg
    maxResponseTime: 500
  - name: zapteryx.com
    url: https://zapteryx.com
  - name: zptx.dev
    url: https://zptx.dev

assignees:
  - zapteryx

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zptx.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/ZPTXDev/status/master/assets/zptx-logo.svg
  name: ZPTX
  introTitle: "**Something amiss?** You've come to the right place."
  introMessage: "This page tracks the status of all of our services. If something isn't working the way you expected it to, let us know over at our [Discord server](https://go.zptx.dev/discord)."
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://zptx.dev
  theme: night
  faviconSvg: https://raw.githubusercontent.com/ZPTXDev/status/master/assets/zptx-logo.svg

i18n:
  allSystemsOperational: All services report as healthy.
  activeIncidentSummary: Started at $DATE with $POSTS update(s)
  incidentOpenedAt: Started at
  incidentClosedAt: Ended at
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS update(s)
  scheduledMaintenanceSummaryStarted: Started at $DATE, lasting for $DURATION minute(s)
  scheduledMaintenanceSummaryStarts: Starts at $DATE, lasts for $DURATION minute(s)
  durationMin: $DURATION minute(s)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
